# https://taskfile.dev

version: '3'


tasks:
  build:
    cmds:
      - go build -o ./bin/bin ./cmd/main.go
  start:
    cmds:
      - ./bin/bin
  dev:
    cmds:
      - nodemon --exec go run ./cmd/main.go
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
